<?xml version="1.0" ?>
<testsuite errors="1" failures="0" name="TestDataObjects-20200522203013" tests="6" time="6.837">
	<testcase classname="TestDataObjects" name="test_01_jpg" time="1.427"/>
	<testcase classname="TestDataObjects" name="test_02_jpeg" time="0.714"/>
	<testcase classname="TestDataObjects" name="test_03_png" time="0.223"/>
	<testcase classname="TestDataObjects" name="test_04_returntype_int_with_list" time="0.208"/>
	<testcase classname="TestDataObjects" name="test_06_multipleinputs" time="4.255"/>
	<testcase classname="TestDataObjects" name="test_05_giving_null" time="0.010">
		<error message="OpenCV(4.2.0) C:\projects\opencv-python\opencv\modules\imgcodecs\src\loadsave.cpp:730: error: (-215:Assertion failed) !buf.empty() in function 'cv::imdecode_'
" type="error">
<![CDATA[Traceback (most recent call last):
  File ".\1.py", line 87, in test_05_giving_null
    response = self.app.post(test_url, data=None, headers=headers)
  File "C:\Users\hp\Anaconda3\lib\site-packages\werkzeug\test.py", line 1016, in post
    return self.open(*args, **kw)
  File "C:\Users\hp\Anaconda3\lib\site-packages\flask\testing.py", line 227, in open
    follow_redirects=follow_redirects,
  File "C:\Users\hp\Anaconda3\lib\site-packages\werkzeug\test.py", line 970, in open
    response = self.run_wsgi_app(environ.copy(), buffered=buffered)
  File "C:\Users\hp\Anaconda3\lib\site-packages\werkzeug\test.py", line 861, in run_wsgi_app
    rv = run_wsgi_app(self.application, environ, buffered=buffered)
  File "C:\Users\hp\Anaconda3\lib\site-packages\werkzeug\test.py", line 1096, in run_wsgi_app
    app_rv = app(environ, start_response)
  File "C:\Users\hp\Anaconda3\lib\site-packages\flask\app.py", line 2464, in __call__
    return self.wsgi_app(environ, start_response)
  File "C:\Users\hp\Anaconda3\lib\site-packages\flask\app.py", line 2450, in wsgi_app
    response = self.handle_exception(e)
  File "C:\Users\hp\Anaconda3\lib\site-packages\flask_restful\__init__.py", line 272, in error_router
    return original_handler(e)
  File "C:\Users\hp\Anaconda3\lib\site-packages\flask\app.py", line 1867, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\hp\Anaconda3\lib\site-packages\flask\_compat.py", line 38, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\hp\Anaconda3\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\hp\Anaconda3\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\hp\Anaconda3\lib\site-packages\flask_restful\__init__.py", line 272, in error_router
    return original_handler(e)
  File "C:\Users\hp\Anaconda3\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\hp\Anaconda3\lib\site-packages\flask\_compat.py", line 38, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\hp\Anaconda3\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\hp\Anaconda3\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\hp\Anaconda3\lib\site-packages\flask_restful\__init__.py", line 468, in wrapper
    resp = resource(*args, **kwargs)
  File "C:\Users\hp\Anaconda3\lib\site-packages\flask\views.py", line 89, in view
    return self.dispatch_request(*args, **kwargs)
  File "C:\Users\hp\Anaconda3\lib\site-packages\flask_restful\__init__.py", line 583, in dispatch_request
    resp = meth(*args, **kwargs)
  File "C:\Users\hp\Desktop\graphs\restapi\Flask API\apk.py", line 325, in post
    img = cv2.imdecode(nparr, cv2.IMREAD_COLOR)
cv2.error: OpenCV(4.2.0) C:\projects\opencv-python\opencv\modules\imgcodecs\src\loadsave.cpp:730: error: (-215:Assertion failed) !buf.empty() in function 'cv::imdecode_'

]]>		</error>
	</testcase>
	<system-out>
<![CDATA[### Setting up flask server ###
<Request 'http://localhost:5000/api' [POST]>
sad
Wen depression is | ur way of life

Finish!
<class 'bytes'>
<Request 'http://localhost:5000/api' [POST]>
happy
Wen teacher gives|extra 2 marks | just to pass u

Finish!
<class 'bytes'>
<Request 'http://localhost:5000/api' [POST]>
Im not saying u r |abnormal, I just dint |recognize a human face

<class 'bytes'>
<Request 'http://localhost:5000/api' [POST]>
Mi face mida edo undiii|darkness ankunta | face eh kanpadatle

<class 'bytes'>
<Request 'http://localhost:5000/api' [POST]>
<Request 'http://localhost:5000/api' [POST]>
happy
Wen teacher gives|extra 2 marks | just to pass u

Finish!
<class 'bytes'>
<Request 'http://localhost:5000/api' [POST]>
happy
The moment u get an | invite for duo | frm ur crush

Finish!
<class 'bytes'>
<Request 'http://localhost:5000/api' [POST]>
happy
Wen ur code compiles|wthout any error | in the first try

Finish!
<class 'bytes'>
<Request 'http://localhost:5000/api' [POST]>
happy
Maths teacher wen he/she|gets to know that|PT teacher is absent

Finish!
<class 'bytes'>
<Request 'http://localhost:5000/api' [POST]>
happy
The moment ur ex | texts u first

Finish!
<class 'bytes'>
<Request 'http://localhost:5000/api' [POST]>
happy
Wen ur code compiles|wthout any error | in the first try

Finish!
<class 'bytes'>
### Tearing down the flask server ###
]]>	</system-out>
	<system-err>
<![CDATA[]]>	</system-err>
</testsuite>
